[package]
name = "hula"
version = "0.1.0"
edition = "2021"
author = ["Zicklag <zicklag@katharostech.com>"]

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
hvm-lang = { path = "../../other/hvm-lang" }
once_cell = "1.18.0"

